name: Code Quality

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create virtual environment and install dependencies
      run: |
        uv venv --python 3.11
        echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
        echo "$(pwd)/.venv/bin" >> $GITHUB_PATH
        uv pip install -e ".[dev]"

    - name: Install pre-commit hooks
      run: |
        pre-commit install

    - name: Run pre-commit
      run: |
        pre-commit run --all-files

    - name: Run type checking
      run: |
        mypy --ignore-missing-imports tyrec.py structured_capture.py struct_editor.py

    - name: Security check with bandit
      run: |
        bandit -r . -f json -o bandit-report.json || true
        bandit -r . || true
