name: Code Quality

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -e ".[dev]"

    - name: Run pre-commit
      run: |
        source venv/bin/activate
        pre-commit run --all-files

    - name: Run type checking
      run: |
        source venv/bin/activate
        mypy --ignore-missing-imports tyrec.py structured_capture.py struct_editor.py || true

    - name: Security check with bandit
      run: |
        source venv/bin/activate
        bandit -r . -f json -o bandit-report.json || true
        bandit -r . || true
