name: Code Quality

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv venv --python 3.11
        uv pip install -e ".[dev]"

    - name: Run pre-commit
      run: |
        uv run pre-commit run --all-files

    - name: Run type checking
      run: |
        uv run mypy --ignore-missing-imports tyrec.py structured_capture.py struct_editor.py || true

    - name: Security check with bandit
      run: |
        uv run bandit -r . -f json -o bandit-report.json || true
        uv run bandit -r . || true
